apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world-api-go
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/argocd/overlays/kind
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello-world-api-go