---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-managed-cluster
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/solthoth/flux-managed-cluster.git