apiVersion: v1
data:
  credentials: ENC[AES256_GCM,data:8jA/JdRweJ6G3//+TFXLOkIybB5wUtpRpePg6QespQOGa1/XQANV8+2nHbJBpVEO5dfcP0fqAv/VUsUv26BEgKWNpSdVcCMD/K6Xz9rzTEaNcO2sYLtcV5w+yCpxJ2RxHba7cLqJh+Fyh8FYp9OpO1hR2fMfnWysqjSCBs187X//aLPFoOkUM/LT73HR5ZC1UL2M3zl4Yyu+2d4bhPIoMCd+mvnrsOko8+2ZYjV6cwtahUoTCuAAE/qBQkft6iUc0/zWvPRHqiGTXjFCCjpXLOQGRF6lJ0qeYh3hAjbMUCPiJ4K5OISEYngXmAweHG6KhGUXKmO0iPl/CXceo88t5tdg0qlej+Qo9TutL08reCqTSEqiwe55p99dlnpGF9T7fa4NedOYWvshk1vLptbnrryPboOIBGf57i+XSVzxaK9BexHzlupJX2UMQcWwOeSNWD8LNZoN5ZLM7vjUBX8D+TgPaefd/zfSPsEtzsdEEEorxjDShMmKaQQQ97bJ5Vdj/X/JKC4B7wfifh9PHF9aqq9mzCnJqhdu2d0w3SyqYzqNlL8JktjaSZ3+y77dcsajkw4IfCeEPEfUrc6LxB6M2BLHy/ipE7r26GZTqiZlbnmf0RG75+QEsEqkYcbAC5to9TNHWh91zidc/H7h4Eoz8gWRm+Jz3xYCL2dkvId8XzwZvJ4B1H1w/q4Lk9hxj64SsCmHFjzR5QRWY90QB0zZtMr1pXgzSOIw9EVpcyfstsuXINlGgHM07bvSG0IKzm5HFYHUMBXhikpk1/Ar2AVhJUwbRWopUfnbut7ts5BPyTgkpWyR76wa9DFG7EHDP18KQVhMUo21+xiQtpIIiAHw9EqJDR9yMaN1svOMw6ZO+VkAcXI30zsk5lWVJsHtpLtbh8j+DZ2Pm7BW4VJE1Eb8bKrvp6l+uYHytYaiO0AixhjWhJOWxJLIACoyQNOTWeJgitUBRrOuXp+1HsrPDcGnvoDo3QdZnKETApIIOFs6WBZnAmXwBF94SqH696NNdYogO+nq31KiI6AYaA8oMq9K0A==,iv:s5d2YmfeQn4/lpi+wBtCp6TdrZr+Boyw52niDTSS0Mg=,tag:Bm0FcTXdk+LvVZnS0j/BVQ==,type:str]
kind: Secret
metadata:
  name: azure-sp-creds
  namespace: crossplane-system
sops:
  age:
    - recipient: age134y3sep4pwznj8y5szwyds98y2szgdevyvvxu475xkex8cfnudzqyj67dm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZFkxcjNYaVVDUXJCSURU
        cnRSTXFINWpjRVFTSDZmTzd6UG14YlRYSVVNClhraUdRcmhBcjVkTXAwMklsanRZ
        MC84bDVVUkRCTVU2SEx5V0c4VnZxaDQKLS0tIHMvYWxQZDdEVHJPL3R5Y0dlRUxU
        SVdNUFBoT2ZCd2lWcGcxVlBVRTltVTQKGYkkg0r0N5LQtCwq4LFkbZ0Q6CDkfbjX
        eRpAzieasGfu5oGY0oUoKHNFzA5hSKQ2X2UU95zmFzZY6xLuXN4yhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T05:08:17Z"
  mac: ENC[AES256_GCM,data:Pfrzf/kl0g+8BKq3IxQTtdA1wakVUtfkUiVyyoNxPU3OgvCXYHBfMyB143+YiOqjyO8X+PERphVZNTx0UEX+KV2yQhbF2QbaSjAj033dj0EsbA42QDXzgfGPDGur60ZdSgj4D5Hf3oRjFeK5vIsVQIkVdf5/woBWoIinorG0+rs=,iv:aWZe6e1aQDVcsLsR49KwD2hDRSYm6yV2Uo04/WYhj8Q=,tag:eOiPb/2wLdr75D6dgANqJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
