apiVersion: v1
data:
  credentials: ENC[AES256_GCM,data:qlMUtjwDHG1MWrkM4WuTp4ZALxNYA7BffWY0dUt4vFsl7u+qwDDDir36l3z7IHpYY919h2UYHyHpzoeB1cD6I82/lExwcnrTwNpRtTtY50AJmHnGKrr0TlDHdCltbSY9qIyvsrz8rE91ehECVNzMOAPG9VAEVNsxlZdaUL83uqStWtLfVM1WYcnf/IYqlXVuj66TnwZKEbx3G9n8icPmYad+R3pq+pWMFCQgNhhLPlxg8aLeK5asODdRnCvWvQLz4xXHw9eJxW32TiBnU8wHRluGRZeOasUTSBV9xtCx1ixSxUgnQLg+eCNREBPHPAN5iW9LkwKz2XfCGOLyyI8ko4xraj0Of5e8BY7Ayzqth1OYxoRNwtVDadPiRoOIArevi93I1r+Oohl+I0kR+QLrFFEHpqvcjIv/RH6fBQwWHF0M0B26ABZeoNhu4RRjigscOKbnh/b7A4r5NYKG9Y0LUpTh6/UupcKXhqL9/MxDjRtM0frraOhMzsH9VqQxT5GXF5uiFDxituLC5WAy07OFHauXn61AWjLCUuoIfXSUJfR9N+62cHpJikkmS1IrcT56/LcNlDjNE4whyT1iON03rBY97+WogAULQM4axlDahKrnNRoitjSYWfEYFxhUyQM5emeo9vwyd3vJZSEzyw8vb6t0Els7D5wDh0t0+4bDW9aAuHL4e+3uxvJ0geOyGA2N7yrgkv5gL7UATS3s4lFwDfBJTBY4cIvETHHoxMJvF/kIlqL3GiHRbc1J8ItbgsYKbG0xTkwQXli687C+pLNkheUJ59aeg6WhWnuoljT69sM2tah/63q/MuAx1yp29U59FO7uNo72oq5uZUaj32zFM+fh1jsMlus0bHr0tgDqUdEH2KqRH542nF3pVUqu8l+ONWS3fOrcpFZKVDeiPJI86TlhldYo6lXjgy7KOyn/iEDaNx81hS8ss8qatwPh+LxREd6YNCx0D8tw3/YBU8jSRf5N6pulAmnH3RLwBttl+PrYH0nnb7w1K+BCxpZGBhGepK526AxEcGSv23j6ML2jYw==,iv:GYFQJT6BbNwcgjG/aK8VQo/TgvnXXbistuw8J6X4Oac=,tag:6PNPYz0/IferhkEf1oRVXg==,type:str]
kind: Secret
metadata:
  name: azure-sp-creds
  namespace: crossplane-system
sops:
  age:
    - recipient: age134y3sep4pwznj8y5szwyds98y2szgdevyvvxu475xkex8cfnudzqyj67dm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOFhTUzAwbENxRnBLeERs
        b2FGS0xsaU4xNWtxUXl3cmlib0h3c0ZrYURZClZaeGpzdFBhbmlwK1I1NGFCdEZa
        ZXRFU2lnNVNEcGRqT3NYN1VTZnJyeEEKLS0tIDVMQ3NKN2lSOVRDRlBqeHhpYzl3
        VW42Z3BVK2NNTE1IRDdtVXBXR3ZXT0kKJtls5Jr748VLDUOqw707lOVBbwdsD2Bj
        8X2qE89gCLSLs/1Fym21aINYW+/FQcUPZ5wkpKmYZybjrZLbt/x8aA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T04:49:33Z"
  mac: ENC[AES256_GCM,data:CK6RnPMP83xq2unww7I5XmV/EecdDC8Jc9LgNjD5AzJVlf/fi4Tb22tRG7tbgQnthEXMDgVGuPkFEOMOaY2dtV98ibhGazz0plQWiAWmpJx3gCZKlHPcGmIzuEZYNjkMGALKUBcuAma931S2s5u5gM2hegW/l0M7kuWhh1mU9r4=,iv:1e6o7FQXgqCKYw5b5TLFmnWUAHqODW68W8ccnC4IhaA=,tag:gBeEKRS9OmI4W0x2ZOGI5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
