---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-config
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./crossplane/overlays/kind/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-providers
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  timeout: 10m
