apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - flux-system

patches:
  - path: argocd.yaml
  - path: apps.yaml
  - path: crossplane.yaml
  - path: crossplane-providers.yaml
  - path: crossplane-config.yaml
  - path: crossplane-compositions.yaml
  - path: crossplane-claims.yaml