apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: super-demo-hello-api
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/solthoth/super-demo-hello-api.git
  ref:
    branch: main
