apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-world-api-go
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/solthoth/hello-world-api.go.git
  ref:
    branch: main
